### ISSUE TITLE
Error checking of input arguments

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#59] opened 2018-08-14 21:50 UTC
When running KINC (See issue https://github.com/SystemsGenetics/KINC/issues/47) If I misspell the input file I get this message:

```
Failed reading from data object file: Unknown error
```
A bit better error message is in order.

**Comment by 4ctrl-alt-del** [comment] 2018-08-15 02:06
I fail to see why this is an issue. It tells you exactly what happened: it failed to read in a data object file. I'm guessing one of the input files you misspelled actually existed and was a blank file or corrupt.

**Comment by spficklin** [comment] 2018-08-15 06:12
The message is unhelpful from an end-user's point of view.  The terminology "data object" isn't clear, and then the phrase "Unknown error" further confuses things.  It really should say that it can't open the file because it doesn't exist.

**Comment by bentsherman** [comment] 2018-08-15 15:10
From looking at the source code (`ace_dataobject.cpp`), the `Unknown error` is actually provided by Qt, not ACE. The problem is that _opening_ the file succeeds, because you can open a file that doesn't exist. It's only when you try to read data that isn't there that an error occurs, and at that point there isn't really any way to know that it was because the file didn't exist.

Maybe we could add the filename to the error message like "Failed reading from data object 'x': ...". I think that would help the user just as well.

**Comment by 4ctrl-alt-del** [comment] 2018-08-16 20:47
Now I understand, Stephen you are correct sorry. I forgot that I always open the file as read AND write so if it doesn't exist it will create it without error.

I will add a "does this file exist?" check when a data object is being opened for input and throw an exception that describes the file not being found.

**Comment by 4ctrl-alt-del** [comment] 2018-10-10 16:39
Resolved in commit 4d0585e731b059b4f6facfb4ab00b393a99e4b98.

**Closed** 2018-10-10 16:39 UTC
Labels: bug
